# fly.toml app configuration file generated for index-drive-prohibitorum on 2023-08-15T14:31:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "index-drive-prohibitorum"
primary_region = "lax"

[http_service]
  internal_port = 5244
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[mounts]
destination = "/opt/alist/data"
source = "data"